name: Pull Request into Master on Push into Devel

on:
  push:
    branches: [ "devel" ]

jobs:
  crete_pull_request:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if PR exists
        run: |
          PR_EXISTS=$(gh pr list -B master -H devel --json number | jq '. | length')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV

      - name: Create Pull Request (if none exists)
        if: env.PR_EXISTS == '0'
        run: gh pr create -B master -H devel --title 'Merge devel into master' --body 'Created by Github action'

