name: Pull Request into Master on Push into Devel

on:
  push:
    branches: [ "devel" ]

jobs:
  crete_pull_request:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: devel
      - name: create pull request
        run: gh pr create -B devel -H origin/master --title 'Merge devel into master' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
