name: Pull Request into Master on Push into Devel

on:
  push:
    branches: [ "devel" ]

jobs:
  crete_pull_request:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request (if none exists)
        if: gh pr list --base master --head devel --json number | jq '. | length > 0'
        run: gh pr create -B master -H devel --title 'Merge devel into master' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

