name: Pull Request into Master on Push into Devel

on:
  push:
    branches: [ "devel" ]

jobs:
  crete_pull_request:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if PR exists
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base master --head devel --json number | jq '. | length > 0')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request (if none exists)
        if: env.PR_EXISTS == 'false'
        run: gh pr create -B master -H devel --title 'Merge devel into master' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

